### ISSUE TITLE
Error: "You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file."

### ISSUE THREAD

**Issue by Alcofribas4** [lewixlabs/TsCard#1]
Hi, 

I'm trying to integrate TsCard in a nodejs project, but I get the following error when compiling:

`$ yarn dev:electron
yarn run v1.19.2
$ cross-env BUILD_ELECTRON=true concurrently -r --kill-others -n "RENDERER,MAIN" "yarn run dev:electron:renderer" "yarn run dev:electron:main"
$ webpack-dev-server --config webpack_config/electron-renderer.development.js
$ webpack --config webpack_config/electron-main.development.js && electron dist/electron-main/main.js
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/alcofribas/Documents/github/debug/MyCrypto
ℹ ｢wds｣: 404s will fallback to /index.html
Type checking and linting in progress...
 ERROR  Failed to compile with 3 errors                                 21:06:17

 error  in ./node_modules/tscard/cards/smartcard.ts

Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export enum CardEvent {
|     Inserted,
|     Removed

 @ ./common/vendor/satochip/satochip.ts 33:0-51 38:42-51 39:41-50 147:16-25
 @ ./common/v2/services/WalletService/deterministic/satochip.ts
 @ ./common/v2/services/WalletService/deterministic/index.ts
 @ ./common/v2/services/WalletService/index.ts
 @ ./common/v2/components/SignTransactionWallets/Keystore.tsx
 @ ./common/v2/components/SignTransactionWallets/index.ts
 @ ./common/v2/components/index.ts
 @ ./common/Root.tsx
 @ ./common/index.tsx

 error  in ./node_modules/tscard/index.ts

Module parse failed: Unexpected token (2:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html
> import pcsc = require('pcsclite');
| import Reader from './reader';
| import SmartCard from './cards/smartcard';

 @ ./common/vendor/satochip/satochip.ts 31:0-32 71:23-29 86:23-29 141:6-12 157:6-12
 @ ./common/v2/services/WalletService/deterministic/satochip.ts
 @ ./common/v2/services/WalletService/deterministic/index.ts
 @ ./common/v2/services/WalletService/index.ts
 @ ./common/v2/components/SignTransactionWallets/Keystore.tsx
 @ ./common/v2/components/SignTransactionWallets/index.ts
 @ ./common/v2/components/index.ts
 @ ./common/Root.tsx
 @ ./common/index.tsx

 error  in ./node_modules/tscard/utilities.ts

Module parse failed: Unexpected token (4:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export default class Utilities {
| 
>     static bytesToHexString(bytesArray : Array<number>) : string {
| 
|         let atrHex : string = "";

 @ ./common/vendor/satochip/satochip.ts 34:0-41 101:25-34 142:39-48
 @ ./common/v2/services/WalletService/deterministic/satochip.ts
 @ ./common/v2/services/WalletService/deterministic/index.ts
 @ ./common/v2/services/WalletService/index.ts
 @ ./common/v2/components/SignTransactionWallets/Keystore.tsx
 @ ./common/v2/components/SignTransactionWallets/index.ts
 @ ./common/v2/components/index.ts
 @ ./common/Root.tsx
 @ ./common/index.tsx
`

The project uses webpack with the following config.js file:

`'use strict';
const path = require('path');

const paths = {
  root: path.join(__dirname, '../'),
  src: path.join(__dirname, '../common'),
  output: path.join(__dirname, '../dist'),
  assets: path.join(__dirname, '../common/assets'),
  static: path.join(__dirname, '../static'),
  electron: path.join(__dirname, '../electron-app'),
  shared: path.join(__dirname, '../shared'),
  modules: path.join(__dirname, '../node_modules')
};

module.exports = {
  // Configuration
  port: 3000,
  title: 'MyCrypto',
  // description < 200 characters
  description: 'MyCrypto is a free, open-source interface for interacting with the blockchain.',
  url: 'https://mycrypto.com/',
  type: 'website',
  // img < 5MB
  img: path.join(paths.assets, 'images/link-preview.png'),
  twitter: {
    creator: '@MyCrypto'
  },
  path: paths,

  // Typescript rule config
  typescriptRule: {
    test: /\.(ts|tsx)$/,
    include: [paths.src, paths.shared, paths.electron],
    use: [{ loader: 'ts-loader', options: { happyPackMode: true, logLevel: 'info' } }],
    exclude: ['assets', 'sass', 'vendor', 'translations/lang']
      .map(dir => path.resolve(paths.src, dir))
      .concat([paths.modules])
  },

  // File resolution
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.css', '.json', '.scss'],
    modules: [paths.src, paths.modules, paths.root],
    alias: {
      modernizr$: path.resolve(__dirname, '../.modernizrrc.js')
    }
  },

  // Vendor modules
  vendorModules: [
    'bip39',
    'bn.js',
    'classnames',
    'ethereum-blockies-base64',
    'ethereumjs-abi',
    'ethereumjs-tx',
    'ethereumjs-util',
    'ethereumjs-wallet',
    'hdkey',
    'idna-uts46',
    'jsonschema',
    'lodash',
    'moment',
    'normalizr',
    'qrcode',
    'qrcode.react',
    'query-string',
    'react',
    'react-dom',
    'react-markdown',
    'react-redux',
    'react-router-dom',
    'react-router-redux',
    'react-transition-group',
    'redux',
    'redux-logger',
    'redux-saga',
    'scryptsy',
    'uuid',
    'wallet-address-validator',
    'whatwg-fetch'
  ]
};
`

Any idea on what may cause the errors? 
It seems related to webpack but I don't know why this specific module fails while other typescript libs seems to load just fine...

Thanks in advance for your help!

**Comment by Alcofribas4** [comment]
Here is also the file 'electron-main.development.js':  

`const path = require('path');
const webpack = require('webpack');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const config = require('./config');

module.exports = {
  target: 'electron-main',
  mode: 'development',
  devtool: 'cheap-module-source-map',

  entry: {
    main: path.join(config.path.electron, 'main/index.ts'),
    preload: path.join(config.path.electron, 'preload/index.ts')
  },

  output: {
    filename: '[name].js',
    path: path.join(config.path.output, 'electron-main')
  },

  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json'],
    modules: [
      config.path.src,
      config.path.modules,
      config.path.root
    ]
  },

  module: {
    rules: [
      /**
       * TypeScript files
       */
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: true,
              cacheCompression: false,
            }
          }
        ],
        include: [
          config.path.src,
          config.path.shared,
          config.path.electron
        ],
        exclude: /node_modules/,
      },

      /**
       * Images
       */
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              hash: 'sha512',
              digest: 'hex',
              name: 'common/assets/[name].[contenthash].[ext]'
            }
          },
          {
            loader: 'image-webpack-loader',
            options: {
              bypassOnDebug: true,
              optipng: {
                optimizationLevel: 4
              },
              gifsicle: {
                interlaced: true
              },
              mozjpeg: {
                quality: 80
              },
              svgo: {
                plugins: [
                  {
                    removeViewBox: true
                  },
                  {
                    removeEmptyAttrs: false
                  },
                  {
                    sortAttrs: true
                  }
                ]
              }
            }
          }
        ],
        include: [
          config.path.assets,
          config.path.modules
        ]
      },

      /**
       * HTML files
       */
      {
        test: /\.html$/,
        loader: 'raw-loader'
      }
    ]
  },

  plugins: [
    new CleanWebpackPlugin(),

    new webpack.EnvironmentPlugin({
      'NODE_ENV': 'development'
    }),

    new ForkTsCheckerWebpackPlugin({
      tsconfig: path.join(config.path.root, 'tsconfig.json'),
      tslint: path.join(config.path.root, 'tslint.json'),
      reportFiles: [
        '**/*.{ts,tsx}',
        '!node_modules/**/*'
      ]
    })
  ],

  externals: {
    'node-hid': 'commonjs node-hid',
    usb: 'commonjs usb'
  },

  node: {
    __dirname: false,
    __filename: false
  }
};
`

**Comment by lewixlabs** [comment]
Hi,
like me, are you trying to integrate tscard in an electorn app?
As starting point you can check my project
https://github.com/lewixlabs/charta

About your issue:

- did you compile tscard (on node_modules/tscard, launching in this folder tsc command) before compile your main typescript electron app?
- after installing & compiling tscard in final js format, you must launch

> ./node_modules/.bin/electron-rebuild

because tscard uses pcsclite, low level nodejs module which uses native pc/sc c++ lib

**Comment by Alcofribas4** [comment]
Hello,

Indeed, I am trying to integrate TsCard in this Electron(and typescript) project: https://github.com/MyCryptoHQ/MyCrypto. I must admit I have rather limited experience with javascript and typescript :-)

I followed your recommendations (tsc compile tscard and rebuild electron) but I still have the same errors. (Since it is a typescript project, is it necessary to compile tscard?)

I use Node 8.16.0, yarn 1.19.2, tsc 2.7.2.

Digging the web, I found this info regarding Babeljs that might be relevant to my issues: https://babeljs.io/docs/en/babel-plugin-transform-typescript

- "This plugin does not support `const enum`"
- "This plugin does not support `export =` and `import` ="

So my issues may be related to the Babel library used in MyCrypto... I will look further and let you know if I find something...

**Comment by lewixlabs** [comment]
> I must admit I have rather limited experience with javascript and typescript :-)

Not very expert me too :D, I come from c#/c++ world, but I noticed in nodejs was simpler build a smartcard library

> I followed your recommendations (tsc compile tscard and rebuild electron) but I still have the same errors. (Since it is a typescript project, is it necessary to compile tscard?)

Yes, typescript helps you to coding in a safer way, but final result, when using electron & nodejs, must be all in js

> So my issues may be related to the Babel library used in MyCrypto... I will look further and let you know if I find something...

I think so but let me know, I'm not expert in Babel so I can't help you.

> I am trying to integrate TsCard in this Electron(and typescript) project: https://github.com/MyCryptoHQ/MyCrypto.

Interesting! Can I ask you, if I can, why do you integrate a smartcard library? What smartcard will you use?

Hi!
Lewix

**Comment by Alcofribas4** [comment]
> Interesting! Can I ask you, if I can, why do you integrate a smartcard library? What smartcard will you use?

The goal is to use a smartcard to store the private keys and use them to sign transactions. For the smartcard, I am using this: https://satochip.io/

Unfortunately, it is quite difficult to access smartcard from browser directly. Alternatively, I may end up using a local server to access the smartcard and communicate with the browser via websocket...

**Comment by lewixlabs** [comment]
> Unfortunately, it is quite difficult to access smartcard from browser directly. Alternatively, I may end up using a local server to access the smartcard and communicate with the browser via websocket...

I confirm, from browser you can't access to smartcard (apdu).
I tried with webusb but latest chrome releases don't allow you to access to usb smartcard reader. 
https://twitter.com/lewixlabs/status/1120643693797683201

From browser maybe you can only access to smartcard certificate.

**Comment by Alcofribas4** [comment]
Yes, if I remember correctly, webusb introduced a vulnerability with yubikey, where 2FA authentication could be abused by a malicious website by communicating through the ccid interface of the yubikey. So Chrome decided to block all smartcard reader devices on webusb...
This article sums it up pretty well: https://www.wired.com/story/chrome-yubikey-phishing-webusb/

**Comment by lewixlabs** [comment]
Ok I close this issue, let me know about your project!
